name: Build APK

on:
  push:
    branches:
      - main  # 当main分支有新的推送时触发构建

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # 根据你的项目需求选择合适的Java版本

      - name: Build APK
        run: |
          cd android/x5  # 进入Android项目目录
          ./gradlew assembleDebug  # 构建Debug版本的APK
          # 如果你需要构建Release版本，可以使用下面的命令
          # ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: utao-apk
          path: android/x5/app/build/outputs/apk/debug/app-debug.apk  # Debug APK的路径
          # 如果你构建的是Release版本，需要修改为对应的路径
          # path: android/x5/app/build/outputs/apk/release/app-release.apk

      - name: Release APK
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')  # 仅在打标签时发布Release
        with:
          files: android/x5/app/build/outputs/apk/debug/app-debug.apk  # Debug APK的路径
          # 如果你构建的是Release版本，需要修改为对应的路径
          # files: android/x5/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
