name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check utao/android/x5 directory content
        run: ls -al utao/android/x5

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        working-directory: utao/android/x5
        run: |
          if [ -f gradlew ]; then
            chmod +x gradlew
          else
            echo "gradlew file not found in utao/android/x5 directory."
            exit 1
          fi

      - name: Build with Gradle
        working-directory: utao/android/x5
        run: ./gradlew build

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: utao-apk
          path: utao/android/x5/app/build/outputs/apk/debug/app-debug.apk

      - name: Output APK information
        run: |
          echo "APK 构建完成，文件路径：utao/android/x5/app/build/outputs/apk/debug/app-debug.apk"
          ls -lh utao/android/x5/app/build/outputs/apk/debug/app-debug.apk
